name: app_review_helper
description: This plugin will make it easier for you to use in-app review with minimal conditions.
version: 0.10.2
homepage: https://github.com/lamnhan066/app_review_helper

screenshots:
  - description: "Introduction"
    path: assets/intro/AppReviewHelperIOS.webp

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.1
  satisfied_version: ^0.4.1
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9
  update_helper: ^0.8.0
  conditional_trigger: ^0.5.1+1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
